
import "./globals.css";
import { Sour_Gummy } from "next/font/google";

import Navbar from "@/components/Navbar/page";
import { Outfit } from "next/font/google";

const sourgummy = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "linkiT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sourgummy.variable} h-screen w-screen bg-white bg-[radial-gradient(100%_50%_at_50%_0%,rgba(0,163,255,0.13)_0,rgba(0,163,255,0)_50%,rgba(0,163,255,0)_100%)]`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
